const money = new Intl.NumberFormat('es-AR', {style:'currency',currency:'ARS',minimumFractionDigits:0,maximumFractionDigits:2});
const fmt = value => money.format(Number(value)||0);
const text = value => String(value ?? '').trim();
const esc = value => text(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const dateFmt = ms => ms ? new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(ms)) : 'Inicio del período';
const rowTime = row => globalThis.ExploraPeriodSettlement?.rowTime?.(row) || Number(row?.createdAtMs||0)||0;
const rowAmount = row => Number(row?.statementAmount ?? globalThis.ExploraPeriodSettlement?.amount?.(row) ?? row?.amount ?? row?.monto ?? 0)||0;
function cleanLabel(row,fallback){return text(row?.statementLabel||row?.expenseLabel||row?.debtLabel||row?.service||row?.detail||row?.notes||row?.reason||fallback)||fallback;}
function proof(row){return Boolean(row?.receiptPdfPath||row?.receiptPath||row?.proofPath||row?.receiptUrl||row?.proofUrl);}
function invoice(row){
  const status=text(row?.arcaStatus||row?.invoiceStatus||row?.fiscalStatus).toLowerCase();
  if(status==='authorized'||row?.cae)return {status:'authorized',label:'Factura ARCA autorizada',number:text(row?.invoiceNumber||row?.comprobanteNumero||row?.cae)};
  if(row?.fiscalEmissionEnabled===false)return {status:'disabled',label:'ARCA desactivada',number:''};
  return {status:'pending',label:'ARCA pendiente / sin autorización asociada',number:''};
}
function entry(row,kind,method=''){
  const amount=rowAmount(row), atMs=rowTime(row);
  const out={id:text(row?.id),label:cleanLabel(row,kind==='income'?'Viaje':'Movimiento'),amount,atMs,date:dateFmt(atMs),proof:proof(row)};
  if(kind==='income'){out.method=method;out.invoice=invoice(row);}
  return out;
}
export function buildClosurePreview({model,driverName,driverUid,createdAtMs=Date.now()}={}){
  if(!model)throw new Error('Falta el modelo del período.');
  const cash=(model.rows?.cash||[]).map(row=>entry(row,'income','cash'));
  const digital=(model.rows?.digital||[]).map(row=>entry(row,'income','digital'));
  const expenses=(model.rows?.expenses||[]).map(row=>{const amount=rowAmount(row),payer=['explora','admin','administrador'].includes(text(row?.payerRole||row?.paidByRole).toLowerCase())?'Explora':'Chofer';return {...entry(row,'expense'),payer,exploraShare:amount/2,driverShare:amount/2};});
  const debts=(model.rows?.debts||[]).map(row=>({...entry(row,'debt'),label:cleanLabel(row,'Deuda interna del chofer')}));
  const internal=[];
  if(Math.abs(Number(model.cashBox||0))>.005)internal.push({kind:'cashbox',label:'Caja Explora 10% del neto del período',amount:Number(model.cashBox)||0,direction:'Asignación interna'});
  for(const row of model.rows?.adjustments||[]){const dir=text(row?.adjustmentDirection||row?.direction);internal.push({...entry(row,'internal'),kind:'settlement',direction:dir==='driver_to_explora'?'Chofer → Explora':dir==='explora_to_driver'?'Explora → Chofer':'Ajuste interno'});}
  const before=Number(model.balance)||0, amount=Math.abs(before), direction=before>0?'driver_to_explora':before<0?'explora_to_driver':'balanced';
  if(amount>.005)internal.push({kind:'closure_liquidation',label:'Liquidación del cierre',amount,direction:direction==='driver_to_explora'?'Chofer → Explora':'Explora → Chofer',note:'Al confirmar, esta liquidación interna lleva el saldo posterior a $0.'});
  return {
    version:'closure_preview_v319',closureId:'',requestId:'',documentNumber:'BORRADOR',createdAtMs,periodStartMs:Number(model.effectiveCutoffMs||0),driverUid:text(driverUid),driverName:text(driverName)||'Chofer',
    notice:'DOCUMENTO NO VÁLIDO COMO FACTURA',subtitle:'Vista previa de cierre operativo, rendición y conciliación interna. Al confirmar se registra la liquidación exacta del saldo y la cuenta posterior queda en $0.',
    liquidationProof:{required:true,path:'',url:'',fileName:'',mimeType:'image/jpeg',uploadedAtMs:0},
    incomes:{cash,digital,cashTotal:Number(model.cash)||0,digitalTotal:Number(model.digital)||0,total:Number(model.grand)||0},
    expenses:{rows:expenses,total:Number(model.expense)||0,paidByDriver:Number(model.expenseCash)||0,paidByExplora:Number(model.expenseDigital)||0,exploraShare:(Number(model.expense)||0)/2,driverShare:(Number(model.expense)||0)/2},
    internal:{rows:internal,total:internal.reduce((s,r)=>s+Math.abs(Number(r.amount)||0),0)},
    debts:{rows:debts,total:Number(model.driverDebtTotal??model.adminDebt)||0,settledByClosure:true},
    reconciliation:{openingBalance:Number(model.openingBalance)||0,periodDifference:Number(model.periodBalance)||0,debts:Number(model.adminDebt)||0,advanceRepayments:Number(model.advanceRepayments)||0,driverPaid:Number(model.driverPaid)||0,exploraPaid:Number(model.exploraPaid)||0,balanceBefore:before,settlementDirection:direction,settlementAmount:amount,balanceAfter:0,cashRemaining:Number(model.cashRemaining)||0,available:Number(model.available)||0,driverShare:Number(model.driverShare)||0,exploraShare:Number(model.exploraShare)||0,cashBox:Number(model.cashBox)||0},
    references:{incomeCount:cash.length+digital.length,expenseCount:expenses.length,debtCount:debts.length,internalCount:internal.length}
  };
}
function rowsHtml(rows){if(!rows?.length)return '<p class="closure-report-empty">Sin movimientos en esta categoría.</p>';return rows.map(row=>`<div class="closure-report-row"><div><strong>${esc(row.label)}</strong><small>${esc(row.date||row.direction||'')}${row.proof?' · comprobante vinculado':''}</small>${row.invoice?`<small>${esc(row.invoice.number||row.invoice.label)}</small>`:''}${row.payer?`<small>Pagado físicamente por: ${esc(row.payer)}</small>`:''}</div><b>${fmt(row.amount)}</b></div>`).join('');}
export function closureReportHtml(s){
  const r=s.reconciliation||{}, dir=r.settlementDirection;
  const beforeLabel=r.balanceBefore>0?'Chofer debe a Explora':r.balanceBefore<0?'Explora debe al chofer':'Cuenta equilibrada';
  const liquidationLabel=dir==='driver_to_explora'?'Chofer → Explora':dir==='explora_to_driver'?'Explora → Chofer':'Sin transferencia';
  return `<div class="closure-report-doc">
    <div class="closure-report-warning"><strong>${esc(s.notice)}</strong><span>${esc(s.subtitle)}</span></div>
    <div class="closure-report-meta"><div><span>Número</span><strong>${esc(s.documentNumber||'BORRADOR')}</strong></div><div><span>Chofer</span><strong>${esc(s.driverName)}</strong></div><div><span>Período desde</span><strong>${esc(dateFmt(s.periodStartMs))}</strong></div><div><span>Generado</span><strong>${esc(dateFmt(s.createdAtMs))}</strong></div></div>
    <section><h3>A. Ingresos por servicios</h3>${rowsHtml([...(s.incomes?.cash||[]),...(s.incomes?.digital||[])])}<div class="closure-report-totals"><span>Efectivo <b>${fmt(s.incomes?.cashTotal)}</b></span><span>Digital <b>${fmt(s.incomes?.digitalTotal)}</b></span><span>Total ingresos por servicios <b>${fmt(s.incomes?.total)}</b></span></div><p>La facturación fiscal se documenta por separado. Este cierre no convierte liquidaciones internas en nuevas ventas.</p></section>
    <section><h3>B. Gastos operativos respaldados</h3>${rowsHtml(s.expenses?.rows||[])}<div class="closure-report-totals"><span>Total gastos <b>${fmt(s.expenses?.total)}</b></span><span>Pagados por chofer <b>${fmt(s.expenses?.paidByDriver)}</b></span><span>Pagados por Explora <b>${fmt(s.expenses?.paidByExplora)}</b></span></div></section>
    <section><h3>C. Movimientos internos / liquidaciones</h3>${rowsHtml(s.internal?.rows||[])}<p>Caja, transferencias, compensaciones y la liquidación del cierre se muestran separados de los ingresos por servicios.</p></section>
    <section><h3>D. Deudas internas del chofer 100%</h3>${rowsHtml(s.debts?.rows||[])}<div class="closure-report-totals"><span>Deudas internas incluidas en el cierre <b>${fmt(s.debts?.total)}</b></span></div><p>Al confirmar el cierre, las deudas incluidas se compensan dentro de la liquidación neta y quedan vinculadas al cierre. El documento no determina por sí solo su tratamiento tributario.</p></section>
    <section><h3>E. Conciliación y puesta a cero</h3><div class="closure-report-ledger"><span>Saldo anterior <b>${fmt(r.openingBalance)}</b></span><span>Diferencia del período <b>${fmt(r.periodDifference)}</b></span><span>Deudas internas <b>${fmt(r.debts)}</b></span><span>Pagos previos del chofer a Explora <b>${fmt(r.driverPaid)}</b></span><span>Pagos previos de Explora al chofer <b>${fmt(r.exploraPaid)}</b></span></div><div class="closure-report-result before"><span>${esc(beforeLabel)}</span><strong>${fmt(Math.abs(Number(r.balanceBefore)||0))}</strong></div><div class="closure-report-liquidation"><span>Liquidación del cierre · ${esc(liquidationLabel)}</span><strong>${fmt(r.settlementAmount)}</strong></div><div class="closure-report-result zero"><span>Saldo posterior al cierre</span><strong>${fmt(r.balanceAfter)}</strong></div></section>
    <section><h3>F. Comprobante de liquidación</h3><div class="closure-report-proof"><span>Dirección <b>${esc(liquidationLabel)}</b></span><span>Importe <b>${fmt(r.settlementAmount)}</b></span><span>Fecha/hora <b>${esc(dateFmt(s.liquidationProof?.uploadedAtMs || s.createdAtMs))}</b></span><span>Referencia <b>${esc(s.liquidationProof?.path || (s.documentNumber==='BORRADOR'?'Se adjunta al confirmar':'—'))}</b></span></div><p>El comprobante de liquidación queda vinculado a este cierre y es la evidencia utilizada para confirmar la puesta a cero de la cuenta.</p></section>
    <section><h3>Resumen documental</h3><div class="closure-report-summary"><span>Ingresos por servicios <b>${fmt(s.incomes?.total)}</b></span><span>Movimientos internos / liquidaciones <b>${fmt(s.internal?.total)}</b></span><span>Deudas internas compensadas <b>${fmt(s.debts?.total)}</b></span></div><p>Los movimientos internos y recuperos/compensaciones de deuda no se suman automáticamente a ingresos por servicios. Este documento no reemplaza facturas ni determina IVA, Ganancias, Monotributo u otro tratamiento tributario.</p></section>
  </div>`;
}
function ascii(value){return text(value).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[–—]/g,'-').replace(/[^\x20-\xFF]/g,'?');}
function wrap(value,max=92){const words=ascii(value).split(/\s+/),out=[];let line='';for(const word of words){if(!word)continue;if((line+' '+word).trim().length>max){if(line)out.push(line);line=word;}else line=(line+' '+word).trim();}if(line)out.push(line);return out;}
function pdfEsc(value){return ascii(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
function reportLines(s){const r=s.reconciliation||{},before=r.balanceBefore>0?'CHOFER DEBE A EXPLORA':r.balanceBefore<0?'EXPLORA DEBE AL CHOFER':'CUENTA EQUILIBRADA',dir=r.settlementDirection==='driver_to_explora'?'CHOFER -> EXPLORA':r.settlementDirection==='explora_to_driver'?'EXPLORA -> CHOFER':'SIN TRANSFERENCIA';const lines=[s.notice,'CIERRE Y RENDICION DE CUENTA',s.subtitle,'',`Numero: ${s.documentNumber}`,`Chofer: ${s.driverName}`,`Periodo desde: ${dateFmt(s.periodStartMs)}`,`Generado: ${dateFmt(s.createdAtMs)}`,'','A. INGRESOS POR SERVICIOS',`Cobros efectivo: ${fmt(s.incomes?.cashTotal)}`,`Cobros digital: ${fmt(s.incomes?.digitalTotal)}`,`TOTAL INGRESOS POR SERVICIOS: ${fmt(s.incomes?.total)}`];for(const row of [...(s.incomes?.cash||[]),...(s.incomes?.digital||[])])lines.push(`- ${row.date||''} | ${row.method==='cash'?'Efectivo':'Digital'} | ${row.label} | ${fmt(row.amount)} | ${row.invoice?.number||row.invoice?.label||''}`);lines.push('','B. GASTOS OPERATIVOS RESPALDADOS',`Total gastos: ${fmt(s.expenses?.total)}`,`Pagados por chofer: ${fmt(s.expenses?.paidByDriver)}`,`Pagados por Explora: ${fmt(s.expenses?.paidByExplora)}`);for(const row of s.expenses?.rows||[])lines.push(`- ${row.date||''} | ${row.label} | ${fmt(row.amount)} | Pagador: ${row.payer||''}${row.proof?' | Comprobante vinculado':''}`);lines.push('','C. MOVIMIENTOS INTERNOS / LIQUIDACIONES');for(const row of s.internal?.rows||[])lines.push(`- ${row.label} | ${fmt(row.amount)} | ${row.direction||''}`);lines.push('','D. DEUDAS INTERNAS DEL CHOFER 100%',`Deudas incluidas/compensadas: ${fmt(s.debts?.total)}`);for(const row of s.debts?.rows||[])lines.push(`- ${row.date||''} | ${row.label} | ${fmt(row.amount)}${row.proof?' | Comprobante vinculado':''}`);lines.push('','E. CONCILIACION Y PUESTA A CERO',`${before}: ${fmt(Math.abs(Number(r.balanceBefore)||0))}`,`LIQUIDACION DEL CIERRE ${dir}: ${fmt(r.settlementAmount)}`,`SALDO POSTERIOR AL CIERRE: ${fmt(r.balanceAfter)}`,'','F. COMPROBANTE DE LIQUIDACION',`Direccion: ${dir}`,`Importe: ${fmt(r.settlementAmount)}`,`Fecha/hora: ${dateFmt(s.liquidationProof?.uploadedAtMs || s.createdAtMs)}`,`Referencia: ${s.liquidationProof?.path || (s.documentNumber==='BORRADOR'?'Se adjunta al confirmar':'—')}`,'El comprobante queda vinculado al cierre y respalda la liquidacion que lleva la cuenta a cero.','','RESUMEN DOCUMENTAL',`Ingresos por servicios: ${fmt(s.incomes?.total)}`,`Movimientos internos / liquidaciones: ${fmt(s.internal?.total)}`,`Deudas internas compensadas: ${fmt(s.debts?.total)}`,'Los movimientos internos y recuperos/compensaciones de deuda no se suman automaticamente a ingresos por servicios.','Este cierre no reemplaza facturas ni determina IVA, Ganancias, Monotributo u otro tratamiento tributario.');return lines.flatMap(line=>line===''?['']:wrap(line));}
function latin1(value){const out=new Uint8Array(value.length);for(let i=0;i<value.length;i++)out[i]=value.charCodeAt(i)&255;return out;}
function concat(chunks){const len=chunks.reduce((s,c)=>s+c.length,0),out=new Uint8Array(len);let p=0;for(const c of chunks){out.set(c,p);p+=c.length;}return out;}
export function createClosurePdf(snapshot){const lines=reportLines(snapshot),perPage=48,pages=[];for(let i=0;i<lines.length;i+=perPage)pages.push(lines.slice(i,i+perPage));const objects=[],add=v=>{objects.push(latin1(v));return objects.length;};const catalog=add('<< /Type /Catalog /Pages 2 0 R >>'),pagesIdx=add('PAGES_PLACEHOLDER'),font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'),pageIds=[];for(const pageLines of pages){let content='BT\n/F1 9 Tf\n42 805 Td\n12 TL\n';for(const line of pageLines)content+=`(${pdfEsc(line)}) Tj\nT*\n`;content+='ET';const contentId=add(`<< /Length ${latin1(content).length} >>\nstream\n${content}\nendstream`);pageIds.push(add(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentId} 0 R >>`));}objects[pagesIdx-1]=latin1(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`);const chunks=[latin1('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n')],offsets=[0];let pos=chunks[0].length;for(let i=0;i<objects.length;i++){offsets.push(pos);const h=latin1(`${i+1} 0 obj\n`),t=latin1('\nendobj\n');chunks.push(h,objects[i],t);pos+=h.length+objects[i].length+t.length;}const xref=pos;let table=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)table+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';table+=`trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;chunks.push(latin1(table));return concat(chunks);}
